travis:
  secure:
    BINSTAR_TOKEN: j1lZG2i84Q5uqVUOVYU66g6C2dbRDmUW/Mf1rJDC1E7pu2Z241VxIpu+/T7g/cB265Sjg2GNpmKo0smFJn3ohYi+kgL0/AK9MREsVCicfqf635jK5vASsJAErvvKgxPfrHr6BVQPadPAQeq0+qf44iZjPhjLMhvwJ4iy9MokQQSJwrQOzcqBqOAe9BVk0LkiOvcjlptWSaKaontlbExQmKASSeD2JI4BBCe2kg67yHxsMfOCn6429ZrsH+xGHoXQnnqIIbvMpQsnDBgc85iRTzN2JybOdcyucr5zF7+E5R3o4wpK4/f+rABeUeBEaaEDpbjKICceJvqKQ4kRxDOZkGQBj6XYxKv3lRZedm919dO9M9a/7McMrOqdbzVP8GKV90RalOSAlR1tmKp+dauY+DuNNP0w6daBiSJw8301idrD7jj2dI/oLd8DXmX2GqFzu6W/yvMgBwkAj45rh6zXoJZYHNcoU9RsQiBmjIp2sYxXa/q+4kECCbtCgpfXtqGHDlGYHMLAW69S+/VGkQKtefu28AKajUpgDq/FEeNXSZmw4eIddtXB95RP6sAedMopamd0CUwz2MoJKzJd+PkM44uY/2+Wdz7I222+3chLSsF1wafq3rLqNjq+0CdrbrOMUzPdYVE7y/VpC7V0YDhiZY4+AeXd8Gkl9CC4EHLeYmk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
